export const ROUTES = {
  PUBLIC: {
    HOME: "/",
    LOGIN: "/login",
    REGISTER: "/register",
    OFFLINE: "/offline",
  },
  NAKES: {
    DASHBOARD: "/nakes",
    PASIEN_LIST: "/nakes/pasien",
    PASIEN_BARU: "/nakes/pasien/baru",
    PASIEN_DETAIL: (id: string) => `/nakes/pasien/${id}`,
    SKRINING_OVERVIEW: "/nakes/skrining",
    SKRINING_BARU: "/nakes/skrining/baru",
    HASIL: "/nakes/hasil",
    MONITORING: "/nakes/monitoring",
    LAPORAN: "/nakes/laporan",
  },
  PATIENT: {
    HOME: "/pasien",
    HASIL: "/pasien/hasil",
    TINDAK_LANJUT: "/pasien/tindak-lanjut",
    RIWAYAT: "/pasien/riwayat",
    EDUKASI: "/pasien/edukasi",
    PROFIL: "/pasien/profil",
    SKRINING: "/pasien/skrining",
    SKRINING_PERSIAPAN: "/pasien/skrining/persiapan",
    SKRINING_PERIKSA_KAMERA: "/pasien/skrining/periksa-kamera",
    SKRINING_CAPTURE: "/pasien/skrining/capture",
    SKRINING_PROSES: "/pasien/skrining/proses",
    SKRINING_BANTUAN: "/pasien/skrining/bantuan",
    ONBOARDING_LANGKAH1: "/pasien/Onboarding/langkah-1",
    ONBOARDING_LANGKAH2: "/pasien/Onboarding/langkah-2",
    ONBOARDING_LANGKAH3: "/pasien/Onboarding/langkah-3",
    ONBOARDING_LANGKAH4: "/pasien/Onboarding/langkah-4",
    ONBOARDING_SELESAI: "/pasien/Onboarding/selesai",
    SKRINING_LANGKAH1: "/pasien/Onboarding/langkah-1",
    SKRINING_LANGKAH2: "/pasien/Onboarding/langkah-2",
    SKRINING_LANGKAH3: "/pasien/Onboarding/langkah-3",
    SKRINING_LANGKAH4: "/pasien/Onboarding/langkah-4",
  },
  CAPTURE: {
    SESSION: (sessionId: string) => `/capture/${sessionId}`,
  },
};
